const demo=document.createElement('div');
demo.className='interactive-demo';
demo.innerHTML=`<div class="eyebrow">TRY THE ENQUIRY FLOW</div><p>Choose a sample job. See what arrives in the business owner’s inbox.</p><form id="demo-form"><div class="demo-fields"><label>Job type<select name="service"><option>Blocked drain</option><option>Hot water repair</option><option>Leaking tap</option></select></label><label>Suburb<input name="suburb" required maxlength="60" value="Marrickville"></label></div><button type="submit" class="button lime">Organise this sample enquiry <span>↗</span></button></form><div id="demo-result" class="demo-result" role="status"><b>Your next enquiry could look like this.</b><p>Try it above. No email is sent and nothing is stored.</p></div></div>`;
document.querySelector('.work-grid').append(demo);
function previewLead(service,suburb){const allowed=['Blocked drain','Hot water repair','Leaking tap'];if(!allowed.includes(service)||typeof suburb!=='string'||!suburb.trim()||suburb.length>60)throw new Error('Choose a listed service and enter a suburb of 1–60 characters.');const result=document.getElementById('demo-result');result.replaceChildren();const heading=document.createElement('b');heading.textContent='✓ Sample enquiry ready for your callback';const detail=document.createElement('p');detail.textContent=service+' · '+suburb.trim();const note=document.createElement('p');note.textContent='Customer acknowledgement: previewed. Business notification: previewed. Next step: call to discuss the job.';result.append(heading,detail,note);result.classList.add('ready');document.querySelector('.lead-card p').textContent=service+' · '+suburb.trim();document.querySelector('#demo-form select').value=service;document.querySelector('#demo-form input').value=suburb;return {service,suburb:suburb.trim(),status:'simulated',sent:false};}
document.getElementById('demo-form').addEventListener('submit',function(event){event.preventDefault();previewLead(this.elements.service.value,this.elements.suburb.value);});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'preview_sample_enquiry',description:'Simulate organising a sample plumbing enquiry and update the visible preview. Sends and saves nothing.',inputSchema:{type:'object',properties:{service:{type:'string',enum:['Blocked drain','Hot water repair','Leaking tap']},suburb:{type:'string',minLength:1,maxLength:60}},required:['service','suburb'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>previewLead(input.service,input.suburb)})).catch(()=>{});}catch{}}

const toggle=document.querySelector('.menu-toggle');const nav=document.getElementById('main-nav');function closeMenu(){toggle.setAttribute('aria-expanded','false');nav.classList.remove('is-open');}toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&toggle.getAttribute('aria-expanded')==='true'){closeMenu();toggle.focus();}});
